datasets:
  EPIC_KITCHENS:
    frames:
      input_subdir: "EPIC_KITCHENS/videos"
      output_subdir: "frames"
    pre_extracted_frames:
      input_subdir: "EPIC_KITCHENS/frames_rgb_flow/rgb"
      output_subdir: "dynamic_images"
    dynamic:
      input_subdir: "EPIC_KITCHENS/frames"
      output_subdir: "dynamic_images"
  EGTEA:
    frames:
      input_subdir: "EGTEA_GAZE_PLUS/Raw_Videos"
      output_subdir: "frames"
    dynamic:
      input_subdir: "EGTEA_GAZE_PLUS/frames"
      output_subdir: "dynamic_images"
  video_extentions:
    supported_extentions: [".mp4", ".MP4"]
  image_extentions:
    supported_extentions: [".jpg", ".JPG", ".png", ".PNG"]
dynamic_image:
  max_samples: 100